# Load distro specific variables
- include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_system == "Linux"

- name: Cinnamon setup
  block:
    - name: cinnamon | set desktop icons
        vars:
          base_key: "/org/nemo/desktop"
        dconf:
          key: "{{ item.key }}"
          value: "{{ item.value }}"
        with_items:
          - { key: "{{ base_key }}/computer-icon-visible", value: "false" }
          - { key: "{{ base_key }}/trash-icon-visible", value: "true" }
  when: ansible_env.GDMSESSION && ansible_env.GDMSESSION == "cinnamon"
