# Load distro specific variables
- include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_system == "Linux"

- name: Linux setup
  block:
    - import_tasks: users/user.yml
    - import_tasks: ansible_setup.yml
    - import_tasks: packages/install_packages.yml
    - import_tasks: packages/install_brave.yml
    - import_tasks: system_setup/apt.yml
    - import_tasks: system_setup/cron.yml
  when: ansible_system == "Linux"
