- name: packages | anydesk | add GPG key
  become: true
  apt_key:
    url: https://keys.anydesk.com/repos/DEB-GPG-KEY
    state: present

- name: packages | anydesk | setup repo (Debian)
  become: true
  apt_repository:
    repo: deb http://deb.anydesk.com/ all main
    state: present
    filename: anydesk-stable

- name: packages | anydesk | install
  become: true
  apt:
    name: anydesk
    update_cache: yes
    state: latest
